export enum AlertMessageType {
  SUCCESS = "SUCCESS",
  ERROR = "ERROR",
  NEUTRAL = "NEUTRAL",
}

export enum EmailType {
  ORDER_CONFIRMED = "ORDER_CONFIRMED",
  SHIPPING_CONFIRMED = "SHIPPING_CONFIRMED",
  DELIVERY_CONFIRMED = "DELIVERY_CONFIRMED",
}
