import type { Metadata } from "next";
import { AuthProvider } from "@/contexts/AuthContext";
import ShowAlert from "@/components/website/ShowAlert";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} body-scrollbar`}>
        <AuthProvider>{children}</AuthProvider>
        <ShowAlert />
      </body>
    </html>
  );
}
